name: Kashirigi
remote_theme: pmarsciell/just-the-docs
logo: "/assets/images/Logo.png"
search-enabled: true
search_tokenizer_separator: /[\s/]+/
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
footer_content: "This is the footer content"
